export type ProspectSegment = 'EXECUTIVE' | 'CAREER' | 'BUSINESS' | 'UNKNOWN';
export type FactState = 'OBSERVED' | 'INDICATED' | 'UNKNOWN' | 'NEGATIVE';
export type FactKey = 'independentBusiness' | 'paidOffer' | 'clientProof' | 'demandSignals' | 'funnelOpportunity' | 'marketingControl' | 'economics' | 'capacity' | 'targetMarket';
export type ProspectTier = 'A' | 'B' | 'C' | 'OUTSIDE_ICP';
export type ProspectEvidence = { url: string; excerpt: string; source: 'WEBSITE' | 'PROFILE' | 'MANUAL'; observedAt: string };
export type ProspectFact = { state: FactState; value: string; reason: string; evidence: ProspectEvidence[] };
export type ProspectReview = { facts: Partial<Record<FactKey, { state: FactState; note: string; url?: string }>>; segment?: string; contactOwnership?: string; contactEmail?: string; note?: string; reviewedAt?: string };
export type ProspectResearch = {
    version: number; researchedAt: string; engine: 'rules' | 'ai' | 'manual'; profileIdentityConfirmed: boolean;
    headline: string; about: string; profileLocation: string; latestPostText: string; lastActivityAt: string | null; activityStatus: 'Active' | 'Inactive' | 'Unknown'; linkedinUrl: string;
    website: string; websiteStatus: 'OWNED' | 'PROFILE_PLATFORM' | 'UNCONFIRMED' | 'NONE';
    segments: ProspectSegment[]; segment: ProspectSegment; facts: Record<FactKey, ProspectFact>;
    pages: { url: string; label: string; status: 'inspected' | 'blocked'; note: string }[]; limitations: string[];
    contacts: { address: string; source: 'linkedin' | 'website' | 'pattern_guess' | 'manual'; url: string; ownership: 'PUBLISHED' | 'DOMAIN_MATCH' | 'GUESSED' | 'UNCONFIRMED' }[];
    description: {url: string; text: string} | null;
    crawl: {version: number; complete: boolean; visited: string[]; pending: string[]; failed: string[]; roots: string[]; matchedHosts: string[]; discovered: number; inspected: number; contactPages: number; descriptionPages: number; stoppedReason: string; candidates: {address: string; url: string; explicit: boolean; contactPage: boolean}[]} | null;
};
export type ProspectAssessment = {
    version: number; researchedAt: string; tier: ProspectTier; segment: ProspectSegment; segments: ProspectSegment[]; score: number;
    businessFit: 'MATCH' | 'POTENTIAL' | 'OUTSIDE_ICP' | 'UNKNOWN'; readiness: 'READY_TO_APPROACH' | 'EARLY' | 'NEEDS_REVIEW'; engagementReady: boolean;
    qualification: {policy: 'EMAIL_ACTIVITY_V1'; qualified: boolean; activity: 'RECENT' | 'INACTIVE' | 'UNKNOWN'; activityAgeDays: number | null; attributableEmail: boolean; needsRetry: boolean};
    contact: { channel: 'EMAIL_READY' | 'EMAIL_NEEDS_VERIFICATION' | 'LINKEDIN_ONLY' | 'UNAVAILABLE' | 'OWNERSHIP_UNCLEAR'; ownership: string; email: string };
    blockers: string[]; unknowns: string[]; cautions: string[]; nextAction: string; research: ProspectResearch; baseResearch: ProspectResearch;
};
export const VERSION: number;
export const RESEARCH_MAX_AGE_DAYS: number;
export const SEGMENTS: ProspectSegment[];
export const SEGMENT_LABELS: Record<ProspectSegment, string>;
export const DEFAULT_TITLES: string[];
export const FACT_KEYS: FactKey[];
export const FACT_LABELS: Record<FactKey, string>;
export const STATES: FactState[];
export const STATE_LABELS: Record<FactState, string>;
export const TIER_LABELS: Record<ProspectTier | 'UNREVIEWED', string>;
export function segmentsFromText(text: string): ProspectSegment[];
export function emptyResearch(input?: Record<string, unknown>, now?: string): ProspectResearch;
export function validateResearch(value: unknown): ProspectResearch;
export function validateReview(value: unknown): ProspectReview;
export function applyReview(research: ProspectResearch, review?: ProspectReview | null): ProspectResearch;
export function assessProspect(research: ProspectResearch, context?: { review?: ProspectReview | null; email?: string; emailProven?: boolean; now?: string }): ProspectAssessment;
export function isContactNow(assessment?: ProspectAssessment | null): boolean;
export function hasAttributableEmail(assessment?: ProspectAssessment | null): boolean;
export function isQualifiedRecord(lead: { pipeline_status: string; email?: string; prospect_assessment?: ProspectAssessment | null }): boolean;
export function hasQualifiedEmail(lead: { pipeline_status: string; email?: string; prospect_assessment?: ProspectAssessment | null }): boolean;
export function pipelineForAssessment(assessment: ProspectAssessment): string;
export function isUnsafeContact(address: string): boolean;
export function isPlatformWebsite(url: string): boolean;
export function hostOf(url: string): string;
export function extractMatchingProfile(response: unknown, slug: string): Record<string, unknown> | null;
export function extractProfileLocation(response: unknown, slug: string): string;
export function extractProfileContactInfo(response: unknown, slug: string): Record<string, unknown>;
