// Editorial starting points, not claims about a real funnel or measured performance.
// Keep this library separate from the user's saved concepts and beliefs.
const evidenceByCategory = {
  messaging:'Compare the traffic promise with page copy; segment landing-page engagement and qualified actions by source.',
  strategy:'Map the full journey and compare qualified outcomes, not only one step’s conversion rate.',
  psychology:'Use interviews or session observations to identify uncertainty, then test a specific change with outcome measures.',
  booking:'Compare bookings, qualification, attendance, and eventual client outcomes before drawing conclusions.',
  nurture:'Check follow-up timing and content; compare attendance and qualified conversations by sequence.',
  proof:'Ask prospects what remained uncertain and test proof matched to that question.',
  measurement:'Define the denominator and downstream outcome before interpreting a rate.',
  page:'Inspect actual page behavior on relevant devices and sources; test the proposed change against qualified outcomes.',
};

function principle(name, category, simpleDefinition, deeperExplanation, whyItMatters, coachingExample, commonMistake, goodImplementation, exception, angle) {
  return { id:`principle:${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`, pillar:'principle', topic:name, category, simpleDefinition, deeperExplanation, whyItMatters, coachingExample, commonMistake, goodImplementation, potentialExceptions:[exception], possibleContentAngles:[angle], angle, recommendedFormat:'Carousel', reason:whyItMatters, evidenceNeeded:evidenceByCategory[category] };
}

export const principles = [
  principle('Message match','messaging','The destination continues the promise that earned the click.','Visitors use the source message to predict what the next page will answer. A changed promise forces them to re-orient.','A coherent transition can preserve relevance before persuasion begins.','A LinkedIn post about founder dependency leads to a page headed “General leadership coaching” with no bridge.','Optimizing the page headline without checking the referring content.','Repeat the specific problem and audience at the top, then introduce the offer.','A broad homepage may serve multiple known traffic sources.','Why a good landing page can fail by starting a different conversation.'),
  principle('Awareness levels','messaging','Match the explanation to what visitors already understand.','Problem-aware visitors need a different bridge from solution-aware visitors.','The wrong depth can confuse or bore people before they evaluate the offer.','An unfamiliar visitor sees “Book executive coaching” before the page names the leadership problem.','Assuming every visitor is ready to compare providers.','Use the traffic source and page opening to establish the next useful level of explanation.','Warm referrals may need less education.','When a booking CTA arrives before the visitor knows what is being solved.'),
  principle('User intent','strategy','Design the next step around the visitor’s current goal.','A visitor exploring options is making a smaller decision than one choosing a provider.','Intent mismatch can make an otherwise clear CTA feel premature.','A visitor reading a diagnostic article is asked immediately to book a sales call.','Treating all visits as buying intent.','Offer an appropriately sized next step and a clear path to deeper commitment.','A direct referral may arrive ready to book.','The same page can work for a referral and fail for an exploratory visitor.'),
  principle('Information scent','messaging','Make links and next steps predict what comes next.','Clear labels help people decide whether a click will answer their question.','Ambiguous navigation adds uncertainty before the next step.','“Discover more” hides whether the destination explains the program or opens Calendly.','Using evocative labels that conceal the action.','Name the destination or outcome of each important link.','Established audience familiarity can make shorthand understandable.','What a CTA label promises before anyone clicks it.'),
  principle('Cognitive load','psychology','Reduce unnecessary mental work during a decision.','Visitors must hold claims, options, and unanswered questions in mind.','Excess complexity can obscure the offer’s actual value.','A coaching page presents six frameworks before explaining who the offer is for.','Equating more explanation with more clarity.','Order information around the decision being made now.','Complex high-stakes offers may require substantial detail.','The cost of explaining the framework before the offer.'),
  principle('Friction','strategy','Identify effort or uncertainty that slows a desired action.','Friction can be mechanical, informational, emotional, or intentional qualification.','Removing the wrong friction can lower lead quality.','A booking form asks for a life story before revealing what the call covers.','Treating every extra step as a defect.','Remove avoidable work while retaining questions that improve fit.','Useful qualification can be worth its effort.','Less friction can produce more bookings and worse calls.'),
  principle('Commitment','psychology','Size the ask to the visitor’s readiness and expected value.','A large commitment requires enough clarity and trust to justify it.','A call may feel disproportionate to an early-stage question.','A cold visitor is asked to book a 45-minute consultation.','Using one high-commitment CTA for every audience.','Explain the call’s purpose or offer a smaller diagnostic step.','A referred prospect may prefer direct booking.','Why a 45-minute call can be too large a first yes.'),
  principle('Social proof','proof','Show credible evidence that relevant people benefited.','Proof works when the visitor can recognize a comparable situation and outcome.','Generic praise may not answer the buyer’s real doubt.','Testimonials say the coach is “amazing” but never describe the change.','Counting testimonials instead of checking relevance.','Pair a specific concern with a credible, permissioned example.','Privacy constraints may limit details.','The difference between praise and proof.'),
  principle('Specificity','messaging','Use concrete details where they clarify a claim.','Specific language makes the audience, problem, and process easier to evaluate.','Vague premium-sounding copy can hide the actual offer.','“Unlock your potential” does not tell a founder what the coaching addresses.','Adding unverified numbers just to sound precise.','Specify audience, problem, and next step without inventing outcomes.','Some offers need breadth; specificity need not mean narrow targeting.','Specificity is not the same as adding a fake number.'),
  principle('Value proposition','messaging','Explain why this offer is worth choosing for this audience.','Value links a relevant problem, mechanism, and expected kind of progress.','A list of features alone may not answer why now or why this.','A page lists six coaching sessions but not the decision they help leaders make.','Substituting credentials for buyer-relevant value.','Connect deliverables to an accurately stated problem and process.','Experienced buyers may already know the category’s value.','Why listing sessions is not yet a value proposition.'),
  principle('Visual hierarchy','page','Use layout to establish what should be noticed first.','Size, contrast, spacing, and order guide scanning.','A correct message can still be hard to find.','Three equal-weight CTAs compete with the offer headline above the fold.','Giving every element the same visual emphasis.','Make the main claim and next action visibly primary.','Accessibility and device differences can change the actual hierarchy.','When the page’s design argues against its copy.'),
  principle('Choice overload','psychology','Limit simultaneous decisions that do not help the current goal.','More options create comparison work, especially when differences are unclear.','Competing paths can delay a useful next step.','A coaching page asks visitors to book, join a newsletter, watch a webinar, and browse services.','Removing useful choice without understanding distinct audiences.','Prioritize one path and make secondary paths clearly subordinate.','Multiple clear paths can help visitors with different intent.','Four calls to action are not four opportunities.'),
  principle('Trust','proof','Make the offer and next step credible and predictable.','People assess whether claims, process, identity, and expectations cohere.','Unanswered uncertainty can block commitment even with strong desire.','A consultation CTA gives no explanation of who runs it or what happens.','Trying to replace clarity with badges or polished visuals.','Explain the real process and show relevant, permissioned proof.','A warm referral may supply trust before the page.','Trust is built by reducing uncertainty, not adding badges.'),
  principle('Objection handling','messaging','Address the specific reasons a qualified visitor hesitates.','Objections can concern fit, time, process, cost, or credibility.','Unanswered fit questions can produce either abandonment or poor-fit calls.','A coach says “for ambitious leaders” but never explains who the program is not for.','Answering generic objections nobody has raised.','Use interviews and calls to prioritize real objections.','Premature objection copy can introduce concerns that were absent.','An FAQ should respond to evidence, not fill space.'),
  principle('Perceived risk','psychology','Account for what the visitor feels they may lose by acting.','Risk may include money, time, privacy, or social exposure.','The same CTA can feel different depending on what remains unknown.','A booking page asks for detailed business data without saying how it will be used.','Assuming a free call feels risk-free.','Set accurate expectations and explain why sensitive information is requested.','Some audiences expect a rigorous application.','A free call can still feel expensive.'),
  principle('Qualification','booking','Check whether a lead fits the offer before or during booking.','Qualification trades some volume for more relevant conversations.','Booking rate alone can hide poor fit.','A coach removes all form questions and sees more calls but more mismatched prospects.','Judging qualification only by form completion.','Ask only questions that change routing or preparation.','For very low-volume funnels, human triage may be better.','More booked calls can mean fewer useful conversations.'),
  principle('Micro vs macro conversions','measurement','Separate intermediate actions from the final business outcome.','A step can improve locally while harming later quality or revenue.','Celebrating one rate can mask a worse funnel.','More calendar clicks occur, but fewer qualified clients sign.','Reporting button clicks as proof of growth.','Track the chain from click to qualified call and client outcome.','Some downstream data may take longer to accumulate.','A higher click rate is not necessarily a better funnel.'),
  principle('Local optimization','measurement','Avoid improving one step at the expense of the whole journey.','Changes can shift who advances, not just how many.','The apparent winner can degrade downstream outcomes.','A shorter application increases submissions but overwhelms the sales team.','Optimizing the most visible metric in isolation.','Predefine a primary outcome and guardrail metrics.','A narrow test can still be useful when downstream impact is known.','The metric that improved while the funnel got worse.'),
  principle('Booking friction','booking','Inspect the effort and uncertainty in scheduling a call.','Availability, time zones, field length, and unclear call purpose affect the booking decision.','A promising visitor may leave at the calendar step.','The landing page is clear, but the calendar asks twelve unexplained questions.','Stopping analysis at the CTA click.','Review the calendar experience and explain any necessary fields.','Some offers legitimately need pre-call screening.','Calendly is not outside the funnel.'),
  principle('Pre-call nurture','nurture','Support a prospect between booking and the conversation.','The gap can be used to clarify expectations and help people arrive prepared.','A booking is not the same as an attended, useful call.','A prospect books two weeks ahead and receives only a calendar invite.','Sending generic hype that creates expectations the call cannot meet.','Send concise, accurate preparation and logistics.','Very short lead times may need only a confirmation.','What happens after the booking button matters.'),
  principle('Show rate','measurement','Measure the share of booked calls that actually happen.','Attendance reflects scheduling context, expectations, reminders, and lead quality.','Booking growth can be misleading if attendance falls.','Booked calls rise after a CTA change, but no-show rate rises too.','Treating show rate as proof of any single cause.','Track show rate alongside source, lead time, and qualification.','Small samples and seasonality can distort the rate.','The booking metric that hides empty calendars.'),
  principle('Funnel continuity','strategy','Keep the promise and context coherent across steps.','Each stage should advance the same underlying decision.','Discontinuity forces visitors to restart their evaluation.','A niche LinkedIn post leads to a generic page and then an unrelated calendar description.','Auditing assets one page at a time.','Read the journey end to end as a prospect from each source.','Different traffic segments may need different routes.','A funnel is a sequence of promises, not isolated pages.'),
  principle('Expectation setting','booking','Tell people what will happen next.','Predictability reduces uncertainty and prevents misaligned calls.','Surprises can lower trust or attendance.','The CTA says “strategy session” but the confirmation does not clarify its purpose.','Using vague language to preserve flexibility.','State duration, purpose, preparation, and who the call is for accurately.','Do not promise a deliverable the team will not provide.','A clear confirmation page can improve the call before it starts.'),
  principle('Mechanism','messaging','Explain how the offer is supposed to produce change.','A mechanism connects the work to an outcome without claiming guaranteed results.','A promise without a plausible path is hard to evaluate.','A coach promises confident leadership but never explains the coaching process.','Inventing proprietary-sounding frameworks without substance.','Describe the actual method and where it may or may not help.','Some buyers rely more on referrals than process detail.','Why an outcome promise needs a credible path.'),
  principle('Relevance','messaging','Help the right visitor recognize that the offer addresses their situation.','Relevance emerges from audience, problem, context, and timing.','A polished page can still feel like it is for someone else.','A founder lands on copy written for “anyone ready to grow.”','Trying to appeal to every coachable person.','Name a real audience and situation without inventing proof.','Broad offers can be relevant if the entry paths are segmented.','A beautiful page can still answer the wrong person.'),
  principle('Clarity vs persuasion','messaging','Make the offer understandable before amplifying desire.','Persuasive claims are difficult to evaluate when the basic proposition is vague.','More emotional copy may increase interest but not informed action.','A hero promises transformation without saying who the program serves.','Adding urgency or adjectives before explaining the offer.','State audience, problem, process, and next step plainly.','Established brands may rely on shared context.','Why clarity often has to precede persuasion.'),
  principle('User goal vs business goal','strategy','Reconcile what the visitor wants with what the business needs.','A funnel should help a person make a useful decision while supporting qualified demand.','Optimizing only for leads can create poor-fit conversations.','A coach wants applications; visitors first want to understand whether coaching fits.','Forcing the business CTA before answering the visitor’s question.','Give the visitor the information needed to choose the right next step.','Direct-response offers can legitimately make the ask early.','The next action should serve both sides of the decision.'),
  principle('Traffic source','measurement','Interpret a page in light of where visitors came from.','Different sources carry different promises and context.','An aggregate rate can hide a source-specific mismatch.','Referral visitors convert while cold social visitors bounce from the same page.','Calling the page broken without segmenting traffic.','Record source and review message continuity for each meaningful segment.','Tiny segments may not support reliable comparisons.','A conversion rate without its traffic source is incomplete.'),
  principle('Traffic temperature','strategy','Distinguish how familiar visitors are with the problem and provider.','Cold and warm audiences differ in trust and information needs.','A direct call CTA may suit one segment and repel another.','A warm referral books quickly; a cold ad visitor needs proof and context.','Using warm-audience results to justify cold-traffic copy.','Match the page and CTA to the source’s likely familiarity.','Temperature is a heuristic, not an observed individual trait.','Why a warm-referral funnel can mislead a cold campaign.'),
  principle('Conversion hierarchy','strategy','Order actions from smaller commitments toward larger ones.','Each step should resolve enough uncertainty for the next.','Skipping necessary context can make a CTA feel abrupt.','A first-time visitor sees “Apply now” before understanding the offer.','Adding steps merely because a framework says to.','Map the decisions and remove steps that do not help.','High-intent visitors may reasonably skip intermediate steps.','The funnel is a ladder of decisions, not a pile of pages.'),
  principle('Form friction','booking','Consider the effort and sensitivity of each form field.','Fields create work and can imply a level of commitment.','Unnecessary fields may lose qualified people.','A first-contact form asks for revenue, team size, and a detailed history.','Removing fields without checking their qualification value.','Keep fields that change routing or preparation; explain sensitive requests.','Application-based offers may need more context.','Every question on a booking form needs a job.'),
  principle('Proof-to-claim matching','proof','Use evidence that supports the specific claim being made.','A testimonial is persuasive only to the extent it addresses the promise or doubt.','Mismatched proof can look decorative.','A page claims operational relief but features praise for the coach’s personality.','Placing any testimonial near any claim.','Match an approved case detail to the exact uncertainty or outcome claimed.','Confidentiality may require less specific proof.','The testimonial does not prove the headline.'),
  principle('CTA hierarchy','page','Make the primary action clear relative to alternatives.','Visual and verbal priority guide attention toward the intended decision.','Equal-weight actions can compete.','Book, download, contact, and subscribe buttons all appear as primary.','Treating every click as equally valuable.','Choose one primary action per context and subordinate useful alternatives.','Multiple audience routes may warrant multiple prominent paths.','If every CTA is primary, none is.'),
  principle('Progressive commitment','psychology','Ask for commitment in proportion to the value already established.','Smaller, useful steps can build context and trust.','A leap to a sales call can feel unjustified.','A diagnostic resource precedes a fit call for a cold audience.','Adding low-value steps simply to warm people up.','Ensure each step helps the visitor decide, not just the business collect data.','High-intent visitors should be able to take a direct path.','A smaller first yes must still be useful.'),
  principle('Decision complexity','psychology','Account for the difficulty of choosing among offers or outcomes.','Multiple packages and uncertain tradeoffs increase comparison work.','Visitors may postpone when differences are unclear.','Three coaching packages differ mostly by abstract labels.','Reducing options without clarifying who each serves.','Explain meaningful differences or guide choice with qualifying criteria.','Sophisticated buyers may want full detail.','Too many packages may be a labeling problem, not a number problem.'),
  principle('Drop-off','measurement','Locate where people stop advancing through a defined journey.','A drop-off is an observation; its cause requires investigation.','Guessing the cause can lead to the wrong fix.','Many reach Calendly, fewer confirm a time.','Calling every exit a copy problem.','Measure step completion and inspect the actual experience before hypothesizing.','Some exits are appropriate self-qualification.','A funnel leak is a location, not a diagnosis.'),
  principle('Conversion paths','strategy','Understand the routes visitors actually take to a useful outcome.','People may move through content, pages, email, and calls in different orders.','One assumed path can hide important entry points.','Prospects read LinkedIn, return directly later, then book from an email.','Attributing every booking to the last page viewed.','Map plausible paths and instrument key transitions.','Attribution may remain incomplete across devices and channels.','The funnel is not always a straight line.'),
  principle('Funnel measurement','measurement','Measure the chain of decisions and outcomes with clear definitions.','Rates only mean something when events, denominators, and time windows are consistent.','Misdefined metrics can reward the wrong change.','A team reports “conversion” without distinguishing clicks, booked calls, and clients.','Using one number to represent the entire funnel.','Define each event and track qualified downstream outcomes with context.','Privacy or low volume may limit precision.','Before optimizing conversion, define what converted.'),
];

function pov(statement, argument, concept, category, optionalCarouselAngle) {
  const related = principles.find(item => item.topic === concept);
  return { id:`pov:${statement.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`, pillar:'pov', topic:concept, category, statement, angle:statement, argument, recommendedFormat:'Text post', optionalCarouselAngle, reason:related?.whyItMatters || argument, learning:{concept, definition:related?.simpleDefinition || '', whyValid:argument, mechanism:related?.deeperExplanation || '', exceptions:related?.potentialExceptions || [], evidenceNeeded:related?.evidenceNeeded || evidenceByCategory[category]} };
}

export const povs = [
  pov('More bookings do not automatically mean a better funnel.','An easier booking path can increase poor-fit calls while leaving client outcomes unchanged.','Qualification','booking','Compare booked calls with qualified calls and clients.'),
  pov('More traffic is not always the answer.','Additional visitors amplify a weak conversion path unless the mismatch is addressed.','Traffic source','strategy','Show the same page under two different traffic sources.'),
  pov('A prettier website is not necessarily a better funnel.','Visual polish cannot substitute for a clear offer and coherent next step.','Clarity vs persuasion','page','Contrast polished but vague copy with plain, specific copy.'),
  pov('Calendly is part of the funnel.','The booking page is where interest becomes a scheduled commitment, so its fields and framing matter.','Booking friction','booking','Map CTA click to confirmed appointment.'),
  pov('The funnel does not end when the call gets booked.','Confirmation, preparation, attendance, and fit are part of the business outcome.','Pre-call nurture','nurture','Show the path from booked to attended call.'),
  pov('Less friction is not always better.','Removing qualification questions may increase bookings while decreasing lead quality.','Friction','booking','Show booking rate rising as qualified-call rate falls.'),
  pov('More testimonials are not automatically stronger proof.','Relevance to the claim matters more than the number of quotes.','Proof-to-claim matching','proof','Match each claim with a specific buyer doubt.'),
  pov('“Book a Call” is not always the right CTA.','The required commitment may be too large for visitors still clarifying the problem.','Commitment','psychology','Compare a direct call ask with a smaller diagnostic step.'),
  pov('The best landing pages continue the conversation that created the click.','Visitors arrive with a question formed by the source; a new topic makes them restart.','Message match','messaging','Trace one promise from post to page.'),
  pov('Generic coaching copy often sacrifices clarity to sound premium.','Abstract language can conceal the audience, problem, and actual offer.','Specificity','messaging','Rewrite a vague premium hero into an accurate proposition.'),
  pov('Conversion rate without traffic context means very little.','A mixed denominator hides differences in intent and source promise.','Traffic source','measurement','Split one aggregate rate by source.'),
  pov('A landing page should not be optimized in isolation.','The prior promise and following booking step shape how page changes perform.','Funnel continuity','strategy','Audit the page between the source and the calendar.'),
  pov('A funnel should not educate more than necessary.','Extra teaching can distract from the decision the visitor came to make.','Cognitive load','psychology','Separate decision-useful teaching from framework exposition.'),
  pov('Short landing pages are not automatically better.','Length matters less than whether each section answers a real question.','Objection handling','page','Compare useful proof with filler copy.'),
  pov('Long applications are not automatically bad.','A longer form can improve fit if its questions do meaningful qualification work.','Qualification','booking','Show the job of each application question.'),
  pov('Coaches often ask for trust too early.','A call request without process clarity or relevant proof demands confidence the page has not earned.','Trust','proof','Locate the first large ask and what precedes it.'),
  pov('Good funnels reduce uncertainty instead of manipulating people.','Clear expectations and evidence help visitors decide without artificial pressure.','Perceived risk','psychology','Replace urgency language with accurate next-step context.'),
  pov('Funnel best practices should be treated as hypotheses, not laws.','A pattern can be useful without proving it will improve a particular audience or offer.','Funnel measurement','measurement','Turn a “rule” into a measurable test.'),
  pov('You can increase conversion rate and still reduce revenue.','A higher intermediate rate can bring less qualified demand or lower-value clients.','Local optimization','measurement','Map a local win against downstream revenue.'),
  pov('Content and landing pages should feel like one continuous conversation.','A coherent sequence lowers the need to reinterpret the offer at every step.','Funnel continuity','messaging','Put the post promise beside the page opening.'),
  pov('The goal is not more leads. It is more of the right leads.','Lead count is not the same as fit, attendance, or client value.','Qualification','strategy','Compare raw lead count with qualified outcomes.'),
  pov('Optimizing a micro-conversion can hurt the macro outcome.','A stronger click or booking rate can move the wrong people further down the funnel.','Micro vs macro conversions','measurement','Trace click, booking, attendance, and client fit.'),
  pov('Proof should answer uncertainty, not simply fill a testimonial section.','A quote should address a real question about the offer or result.','Social proof','proof','Organize proof by buyer concern rather than page section.'),
  pov('A high booking rate can hide poor qualification.','Without downstream fit data, calendar completion tells only part of the story.','Qualification','booking','Put booked and qualified rates on the same chart.'),
  pov('Every extra funnel step should justify its existence.','A step should help the visitor decide or help the business serve them better.','Conversion hierarchy','strategy','Ask what decision each step enables.'),
  pov('Clarity usually matters before persuasion.','If visitors cannot identify the offer and next step, emotional language has little to anchor to.','Clarity vs persuasion','messaging','Rewrite a persuasive but ambiguous hero.'),
  pov('A funnel’s job is not to convince everyone.','A good path lets poor-fit visitors opt out while helping qualified people advance.','Qualification','strategy','Show how clear fit criteria protect both sides.'),
];

function exercise(topic, angle, hypotheticalBefore, concept, category, recommendedFormat='Carousel') {
  const related=principles.find(item=>item.topic===concept);
  return {id:`transformation:${topic.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,pillar:'transformation',topic,category,angle,hypotheticalBefore,concept,recommendedFormat,reason:related?.whyItMatters || 'A focused before/after exercise that teaches the reason for the change.',learning:{concept,definition:related?.simpleDefinition || '',whyValid:related?.whyItMatters || '',mechanism:related?.deeperExplanation || '',exceptions:related?.potentialExceptions || [],evidenceNeeded:related?.evidenceNeeded || evidenceByCategory[category]}};
}
export const transformations = [
  exercise('Vague coaching hero','Replace a vague promise with audience, problem, and accurate outcome.','Unlock your potential and become the leader you were meant to be.','Specificity','messaging'),
  exercise('Weak CTA','Make the next action and its purpose explicit.','Take the next step.','Information scent','messaging','Text post'),
  exercise('Generic testimonial section','Turn broad praise into proof that answers a buyer concern.','Working with this coach was amazing.','Proof-to-claim matching','proof'),
  exercise('Overloaded booking form','Remove or justify fields based on qualification value.','Tell us your full career history, revenue, team size, and biggest fears before selecting a time.','Form friction','booking'),
  exercise('Confirmation page','Clarify what happens after a call is booked.','Thanks. See you soon.','Expectation setting','booking','Text post'),
  exercise('Nurture email','Replace generic excitement with useful preparation.','We are excited for your upcoming call! Big things are coming.','Pre-call nurture','nurture','Text post'),
  exercise('Competing CTAs','Give one action visual priority while keeping useful secondary paths.','Book a call. Download a guide. Watch a webinar. Subscribe. Contact us.','CTA hierarchy','page'),
  exercise('Offer clarity','Explain who the coaching serves and what the engagement actually involves.','Transform your life with our signature coaching experience.','Value proposition','messaging'),
  exercise('Landing-page hierarchy','Move the core decision information ahead of framework exposition.','Our methodology: five phases and twelve competencies.','Visual hierarchy','page'),
  exercise('Ad-to-page message match','Continue the source promise at the top of the destination.','Ad: Escape founder dependency. Page: Reach your full leadership potential.','Message match','messaging'),
];

function hunt(topic, angle, category, concept) {
  const related=principles.find(item=>item.topic===concept);
  return {id:`breakdown:${topic.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,pillar:'breakdown',topic,category,angle,recommendedFormat:'Carousel',reason:`${related?.whyItMatters || 'This could reveal a useful funnel tension.'} Check a real funnel before claiming it applies.`,requiresEvidence:true,learning:{concept,definition:related?.simpleDefinition || '',whyValid:'This is an observation to investigate, not a claim about an unseen funnel.',mechanism:related?.deeperExplanation || '',exceptions:related?.potentialExceptions || [],evidenceNeeded:'Capture the actual page, CTA destination, and any relevant traffic message. Mark unseen steps unknown.'}};
}
export const breakdowns = [
  hunt('Competing CTAs','Find a coach whose page presents several equal-priority next steps.','page','CTA hierarchy'),
  hunt('LinkedIn to generic homepage','Find a coach sending a specific LinkedIn promise to a generic homepage.','messaging','Message match'),
  hunt('Vague testimonials','Find a coaching page whose testimonials praise the person but not the claimed outcome.','proof','Proof-to-claim matching'),
  hunt('Cold traffic to Calendly','Find a cold-traffic path that links straight to a calendar.','booking','Commitment'),
  hunt('Long application form','Find a coach with a long application and inspect what each question is for.','booking','Qualification'),
  hunt('Positioning mismatch','Compare a coach’s public positioning with the visible website opening.','messaging','Funnel continuity'),
  hunt('Strong content, weak path','Find a coach with specific content but an unclear path to the offer.','strategy','Conversion paths'),
];

export const builtInIdeas=[...principles,...povs,...transformations,...breakdowns];

