// Prepared editorial starting points. These are conversion-focused arguments,
// not claims of measured performance, and require no provider request to browse.
const starters = [
  ['busy-calendar','pov','Qualified bookings','A full calendar can hide an empty pipeline.','Contrast booked calls with attended, qualified conversations. Show a clearly illustrative funnel with no invented results; explain which downstream questions a coach should ask.','Plenty of calls, but too few suitable clients.','Challenges a visible vanity metric and connects content to the buyer’s actual sales problem.'],
  ['booking-decision','transformation','Call invitation','Your button says “Book a call.” Your buyer is asking “What am I agreeing to?”','Compare a vague call invitation with one that explains purpose, fit and the next step. Only use offer details supplied by the user; otherwise demonstrate the questions to answer.','People hesitate because the call commitment is unclear.','Makes a small, concrete copy improvement visible without promising a conversion lift.'],
  ['proof-question','principle','Useful proof','“Amazing coach” is a compliment. It still leaves the buyer’s question unanswered.','Show how to match real testimonial evidence to a specific concern, such as relevance or process. Use labelled placeholders instead of inventing a customer quote or result.','Praise on the page does not address the buyer’s uncertainty.','Demonstrates a practical way to evaluate proof instead of asking for more testimonials.'],
  ['beautiful-vague','transformation','Offer clarity','A beautiful page can still make the right buyer ask: “Is this for me?”','Use an illustrative vague hero and show how audience, situation and the actual offer make it more specific. Do not manufacture a service promise.','The page looks polished but the offer is hard to identify.','Creates an easy-to-see before/after around a problem a coach can recognize.'],
  ['wrong-leads','pov','Buyer fit','If everyone can see themselves in your offer, who is it actually for?','Explain the trade-off between broad appeal and recognizable fit. Demonstrate clear positive fit criteria and respectful exclusions for a hypothetical coaching offer.','Broad messaging attracts conversations the coach cannot serve well.','Links positioning to the quality of sales conversations.'],
  ['content-handoff','principle','Content to offer','Your post answered one problem. Your homepage started a different conversation.','Place an illustrative post promise beside a generic page opening. Show how the landing page can continue that specific question without adding a new offer.','Engaged readers lose context on the way to the offer.','Connects the content the buyer already creates to the next commercial step.'],
  ['form-purpose','pov','Application questions','A shorter application is only better if it still asks the questions that matter.','Sort illustrative form questions into qualification, preparation and unnecessary effort. Explain what each retained question enables and the trade-off in removing it.','A form is shortened without considering client fit.','Offers a useful counterpoint to blanket advice about removing friction.'],
  ['after-booking','principle','Call preparation','The booking is done. The decision to show up is still ahead.','Map the path from booking to attendance. Show where accurate purpose, logistics and preparation belong, without assuming a particular reminder sequence improves results.','Booked prospects arrive unprepared or with mismatched expectations.','Expands the discussion beyond the button into a problem that affects real calls.'],
  ['objection-location','transformation','Objection handling','The answer your buyer needs might be three scrolls below the decision.','Use an illustrative page outline to move a relevant answer next to the corresponding ask. Keep legitimate detail available; demonstrate placement rather than deleting nuance.','Important answers are separated from the action they support.','Turns abstract objection handling into a concrete page-layout lesson.'],
  ['framework-first','transformation','Buyer language','Your buyer has a problem. Your headline introduces a framework.','Contrast a methodology-led introduction with one that names the buyer’s situation first, then explains the actual process. Preserve accurate offer details.','Visitors cannot connect a branded method to their own problem.','Gives coaches a recognizable copy exercise they can apply to their own page.'],
  ['price-objection','pov','Understanding value','“Too expensive” does not tell you which part of the offer was unclear.','Separate affordability, perceived value and poor fit as possibilities. Show questions a coach can investigate before discounting; never claim the objection has one cause.','Discounting is used before understanding a buyer’s hesitation.','Addresses a commercially important objection with a more useful diagnostic approach.'],
  ['cta-priority','transformation','Page priorities','Five next steps can leave a visitor unsure which one matters.','Sketch a page with competing actions, then give one suitable action priority. Keep secondary paths where they serve a different level of readiness.','A page presents several actions with equal emphasis.','Produces a clear visual comparison suited to a carousel or Miro walkthrough.'],
  ['earned-call','principle','Commitment','A free call can still ask for a lot of trust.','Explain the non-price commitments of a call: time, attention and sharing context. Show how accurate expectations and relevant evidence can make the choice clearer.','The offer treats a free call as a risk-free decision.','Reframes a familiar CTA from the prospect’s point of view.'],
  ['cold-vs-referral','pov','Traffic context','Your referral funnel may be borrowing trust your content visitors do not have.','Compare what a referred visitor and a first-time reader may already know. Identify which context the page needs to supply without assuming all visitors behave alike.','A funnel is evaluated only through warm referrals.','Explains why a familiar setup may need different context for a new audience.'],
  ['specific-not-hype','transformation','Specific outcomes','“Unlock your potential” asks the buyer to write the meaning for you.','Rewrite a clearly labelled hypothetical promise around a concrete situation and a credible process. Avoid guaranteeing transformation or inventing client outcomes.','Broad aspirational language hides what the coach actually helps with.','Offers a memorable example with visible practical value.'],
  ['measure-whole-path','principle','Meaningful metrics','More clicks. Fewer good-fit calls. Which number would you celebrate?','Use an explicitly hypothetical comparison without fabricated statistics to distinguish click-through, booking, attendance and qualification. Explain why one local metric cannot decide the whole funnel.','Optimization decisions stop at the earliest improving metric.','Connects a provocative question to a useful measurement habit.'],
  ['proof-honesty','pov','Credible claims','A client’s result can be impressive without being a promise to the next buyer.','Explain how to present a real result with relevant context and limitations. If no actual result is supplied, demonstrate the structure using placeholders, not invented numbers.','A case study blurs evidence and an implied guarantee.','Builds credibility by showing how to make proof both persuasive and accurate.'],
  ['offer-before-redesign','principle','Funnel diagnosis','Before you redesign the page, ask someone to explain the offer back to you.','Describe a simple clarity check: who it serves, what it helps with, how it works and the next step. Treat the answers as diagnostic input, not proof of conversion performance.','Design changes are proposed before the messaging problem is understood.','Gives the reader a useful first action and demonstrates thoughtful strategy.'],
];

export const starterIdeas = starters.map(([key,pillar,topic,hook,angle,buyerProblem,whyRelevant])=>({
  id:`starter:${key}`,pillar,topic,hook,angle,buyerProblem,whyRelevant,generatedBy:'starter',searchQuery:'',sourceId:'',
}));
